matrix:
  include:
  - name: "Windows Test"
    os: windows
    language: node_js
    node_js: "10.13.0"
    install:
    - cd test
    - npm i
  - name: "Linux Test"
    language: node_js
    node_js: "10.13.0"
    os: linux
    dist: xenial
    sudo: false
    install:
    - cd test
    - npm i
  - name: "OSX Test"
    os: osx
    language: node_js
    node_js: "10.13.0"
    install:
    - cd test
    - npm i
  - name: "OSX Build"
    os: osx
    if: commit_message =~ /^:hammer:/
    language: cpp
    compiler: clang++
    script:
      - chmod +x src/osx.sh && src/osx.sh


deploy:
  on:
    condition: language = cpp
  provider: releases
  name: "Binary for OSX"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  file:
    - "src/freeimage.dylib"
