name: Build OSX FreeImage

on:
  workflow_dispatch

jobs:
  Build:
    if: contains('["raub"]', github.actor)
    runs-on: macos-11

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          cache: 'npm'

      - name: Build
        run: |
          chmod +x src/osx.sh && src/osx.sh
      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: osx-${{ github.run }}-${{ github.sha }}
          name: FreeImage OSX
          body: OSX FreeImage binaries at ${{ github.sha }}
          files: src/build/*
